### ISSUE TITLE
"C64DebuggerPluginShowPic.cpp" source missing

### ISSUE THREAD

**Issue by 4ch1m** [slajerek/RetroDebugger#12]
Hi there,

just did a fresh clone... and tried to compile the sources.

```
mkdir build
cd build
cmake ./../
-- Configuring done
CMake Error at CMakeLists.txt:191 (add_library):
  Cannot find source file:

    /<...>/RetroDebugger/src/Plugins/ShowPic/C64DebuggerPluginShowPic.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at CMakeLists.txt:191 (add_library):
  No SOURCES given to target: Plugins
```

The `C64DebuggerPluginShowPic.cpp` seems to be missing in SCM?

Thanks!

**Comment by slajerek** [comment]
Thanks, this file is actually not needed by the RetroDebugger, it is just a plugin with some demo effect. Fixed with commit aaf0bfd   Note this file will be added as an example how to make a plugin with some upcoming release.
