### ISSUE TITLE
D64 autostart fails on apple silicone (M1)

### ISSUE THREAD

**Issue by chran554** [slajerek/RetroDebugger#17]
**Describe the bug**
I can start the Retro Debugger application (by double click on the executable in Finder).
However I can not make any program run that is loaded from disc .d64 or .prg .

**To Reproduce**
1. Start Retro Debugger by double click program in Finder
2. Choose a .d64 file after selecting File | Open in menu. ([http://csdb.dk/getinternalfile.php/85044/GIANA SISTERS.D64](https://csdb.dk/release/download.php?id=110874)
3. Got messages/notifications "inserted nnn ..." and "loaded from $0801 to $A8FF"
4. Nothing happens
5. Choose Code | Continue and it executes a few lines from $0801 but fails on $0811 "BRK"

**Expected behavior**
Me playing Giana Sisters all night long and with a happy smile editing diamond characters to change the animations

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.5.1 (mac with apple ARM silicon M1 processor)
 - Version 0.64.64

**Additional context**

<img width="1055" alt="Greenshot 2023-08-23 22 27 28" src="https://github.com/slajerek/RetroDebugger/assets/13197030/6d91bd78-efd0-4881-9f0b-a8889fbc4566">

**Comment by slajerek** [comment]
I tested the file and works for me on Monterey Silicone M2 Max. The problem you are experiencing is a crash of game loader.

This could be related to Settings configuration that is not suitable for auto run of D64 programs. Could you please check if you have a proper configuration to autostart of D64 files:
- "Load first PRG on disk insert" is selected
- "Always JMP to loaded addr" is not selected
- "Reset C64 on PRG load" is selected "Hard reset"
- "Wait after Reset" is set enough so kernal finishes its initialization (e.g. 2000ms)

Problem you have may also be related to inserted cartridge, e.g. some cartridges have their menus and change memory configuration and some loaders, cracks etc do not init this correctly on startup and may also crash.

Note, some loaders are still not compatible and I am still trying to understand why they fail (Spindle for example), it seems some kernal variables are not set, however your Giana Sisters D64 file is not that case.

**Comment by chran554** [comment]
ID-10-T error
