### ISSUE TITLE
Reset keyboard mapping on mac

### ISSUE THREAD

**Issue by danielschonfeld** [slajerek/RetroDebugger#22]
**Describe the bug**
Can't find which files to delete/how to reset keyboard mapping that i've "set as default"

Also an odditiy which only shows it self sometimes, i'll type the word "LIST" for instance, and sometimes the PET ASCII symbols will be typed instead of the character.  Can't say much more about this, because i haven't yet found a rhyme or reason this happens and what triggers it.

**Desktop (please complete the following information):**
 - OS: Mac
 - Version Ventura 13.4

**Comment by slajerek** [comment]
This is already on my to do list. You can reset the mapping now manually by deleting `keymap.dat` file from app settings, it is located at `~/Library/RetroDebugger/keymap.dat`

**Comment by MarcinSkoczylasSH** [comment]
This has been fixed in a69c371

**Comment by slajerek** [comment]
This has been fixed in a69c371
