### ISSUE TITLE
1541 Memory Breakpoints added to C64 Memory Breakpoints

### ISSUE THREAD

**Issue by KoboldSoftware** [slajerek/RetroDebugger#24]
Right mouse button on an address in "1541 Memory" window, select checkbox "Breakpoint: Write" and the address is added to "C64 Memory Breakpoints" window instead.

**Comment by slajerek** [comment]
That has been fixed already, please check devel builds, it will be released soon: https://drive.google.com/drive/folders/1RlRRQRnkXQuDhylgCya0h2OWAJFfhxhB

The problem was because 1541 Drive memory view showed C64 memory by mistake.

**Comment by KoboldSoftware** [comment]
Great, thank you very much :)

**Comment by slajerek** [comment]
Released with a69c371
