### ISSUE TITLE
"$" input in C64 Data watch causes crash

### ISSUE THREAD

**Issue by c64cryptoboy** [slajerek/RetroDebugger#32]
**Describe the bug**
C64 Data watch will crash the Retro Debugger if, when adding a new watch point, I start by typing "$"

**To Reproduce**
1. "C64"->"C64 Data watch"
2. In C64 Data Watch window, click "+"
3. In "Add watch point" text area, begin address by typing "$" for an immediate crash (and program quits)

**Expected behavior**
To either block "$" characters (as they're not needed) or to tolerate addresses that start with "$"

**Desktop**
 - OS: Windows 11 Home
 - Retro Debugger v0.64.66

**Comment by slajerek** [comment]
Thanks, I've fixed this and bugfix will be released in next version.

**Comment by slajerek** [comment]
Fixed with 0.64.68
