### ISSUE TITLE
Monitor console prompt has no cursor

### ISSUE THREAD

**Issue by mrdudz** [slajerek/RetroDebugger#37]
... this makes the console pretty annoying to use

**Comment by slajerek** [comment]
Interesting, what do you exactly mean by cursor? You do not see that white rectangle which is a cursor?

**Comment by mrdudz** [comment]
Built from git head, running on linux

However, now it appears to work - weird :) (And just to make it clear, i am talking about "c64 monitor console", not the memory views etc - i get a green cursor now :))

I can't reproduce it now, closed all windows, restarted the debugger, reopened the monitor window... its still working. no clue what happened the other day. Will re-open when i see it again and i can reproduce :)
