### ISSUE TITLE
Linux build: libglew-dev needed

### ISSUE THREAD

**Issue by fieserWolF** [slajerek/RetroDebugger#4]
**Describe the bug**
Compilation fails on Debian 5.14.9-2 (2021-10-03) x86_64 GNU/Linux .

**Console output**
[100%] Linking CXX executable retrodebugger
/usr/bin/ld: cannot find -lGLEW

**Desktop (please complete the following information):**
 - OS: Linux
 - Version Debian 5.14.9-2 (2021-10-03) x86_64 GNU/Linux

**Additional context**
OpenGL Extension Wrangler seems to be missing. Please, just include this information in README.md.

fix: sudo apt install libglew-dev

**Comment by slajerek** [comment]
Thanks, good point. I've added this information to the README.
