### ISSUE TITLE
Missing gcc compiler flag

### ISSUE THREAD

**Issue by thecky** [slajerek/RetroDebugger#43]
Hi,

currently the code doesn't compile under "Arch" with GCC 14.1.1.
The fix is really simple, just add CMAKE_C_FLAGS to CMakeLists.txt, like it's already done with CMAKE_CXX_FLAGS.
So, that you have these lines:

`set (CMAKE_CXX_FLAGS "-fpermissive")`
`set (CMAKE_C_FLAGS "-fpermissive")`

This is already addressed in issue #31 (atleast in the first posts).

Regards,
Thomas

**Comment by slajerek** [comment]
Thanks, I've added this fix. On my Debian that was not necessary. It will be released with 0.64.68

**Comment by slajerek** [comment]
Thanks
https://github.com/slajerek/RetroDebugger/blob/master/CMakeLists.txt
