### ISSUE TITLE
Changing keymap?

### ISSUE THREAD

**Issue by thecky** [slajerek/RetroDebugger#45]
Hi,

is there a way to change the keymap under linux for the used vice version?
I miss several keys (like *, left arrow, ...). In my native vice version the keymapping is fine and can also be altered.

Thx

**Comment by slajerek** [comment]
Yes, in Settings for C64 there's view to edit keymal, please let me know if that works for you.

**Comment by thecky** [comment]
Yes, there is a entry in the menu ("Keyboard mapping"). But after clicking, no window / view appears on the workspace to change the mapping.
There's only a hook at the end of the menuentry and nothing else.
Can I enable a logging / verbose mode to track down the problem?

Btw: I use arch-linux

**Comment by slajerek** [comment]
Interesting, then this is a bug. You should see "Keyboard mapping" tool like this:

<img width="641" alt="Screenshot 2024-05-16 at 21 37 24" src="https://github.com/slajerek/RetroDebugger/assets/1021783/e498e790-668c-4f7e-91f2-09e866e9f740">

I wonder if this is related to arch-linux, I've just tested this on macOS and works OK, I'll check this also on Linux.

**Comment by thecky** [comment]
Okay, this screen isn't show. After taking a look into the code, I found two KeyMapping related files:
`src/Screens/CViewC64KeyMap.cpp (and .h)
src/Views/C64/CViewC64KeyMap.cpp (and .h)`

The title "C64 Key mapping" from your screenshot is found in the file under "Views/C64". But my build seems to use the code from the Screens-include.

I modified my CMakeLists.txt and replaced the include with the path "src/Views/C64/CVieC64KeyMap.cpp" and after a rebuild, the window is present.

**Comment by slajerek** [comment]
Is this fixed now @thecky ?

**Comment by thecky** [comment]
With the fix the keymap is visible and I haven't noticed any other drawback yet.
So, if it works / compile on your system everything should be fine and the issue can be closed.

**Comment by slajerek** [comment]
Thanks
