### ISSUE TITLE
Missing file: src/Views/C64/AllGraphics/CViewC64AllGraphics.cpp

### ISSUE THREAD

**Issue by UffeJakobsen** [slajerek/RetroDebugger#49]
CMakeLists.txt has a reference to:

src/Views/C64/AllGraphics/CViewC64AllGraphics.cpp

But that file is not in the repo...

**Comment by slajerek** [comment]
This file is not required, it is a leftover. You can safely remove it from CMakeLists.txt and I'll fix this in repo, thanks for reporting - I thought I fixed that all :)

**Comment by UffeJakobsen** [comment]
Thx - closing issue :+1:
