### ISSUE TITLE
Linux build: undefined reference to symbol 'XSynchronize'

### ISSUE THREAD

**Issue by fieserWolF** [slajerek/RetroDebugger#5]
**Describe the bug**
Compilation fails on Debian 5.14.9-2 (2021-10-03) x86_64 GNU/Linux .
MTEngineSDL was built beforehand. It is in ../.. as it should be.

**Console output**
/usr/bin/ld: ../../MTEngineSDL/build/libMTEngineSDL.a(SYS_Platform.cpp.o): undefined reference to symbol 'XSynchronize'
/usr/bin/ld: /lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

**Desktop (please complete the following information):**
 - OS: Linux
 - Version Debian 5.14.9-2 (2021-10-03) x86_64 GNU/Linux

**Additional context**

**Comment by slajerek** [comment]
Thanks. I've added X11 libs to CMakeLists: https://github.com/slajerek/RetroDebugger/commit/170c73845b510f8fa1c9b7d33b5c5fc57afaad76
