### ISSUE TITLE
F9 - Main Menu not working

### ISSUE THREAD

**Issue by Myriad991** [slajerek/RetroDebugger#55]
The F9 key does not show the main menu. Other keys e.g., F10/F11 function as normal. I cannot find anyone else having the same issue, did I miss a change/documentation or is it my setup?

SETUP
Macbook Pro M1
UTM virtual box
Ubuntu 22.04 64bit Aarch64
RetroDebugger successfully built from source

I checked whether MacOS was blocking/reserving the F9 key but cannot find anything. No idea what to check anymore, any ideas?

**Comment by slajerek** [comment]
There's no such thing as F9 main menu in Retro Debugger anymore, it was in old C64 Debugger only. You have all menu items now in the Settings menu from main window's menubar.

<img width="464" alt="Screenshot 2024-07-10 at 12 19 32" src="https://github.com/slajerek/RetroDebugger/assets/1021783/436878f4-326b-436a-add8-b21926de8fc2">

**Comment by Myriad991** [comment]
Much appreciated, I was hoping that was the case. Was following the/a old manual. 

Just a novice user at moment, but I have to say it already looks and works absolutely awesome! Many thanks!!!
