### ISSUE TITLE
Compiled the source but cannot find the debugger

### ISSUE THREAD

**Issue by cbmeeks** [slajerek/RetroDebugger#61]
I compiled and built the source in Linux.  However, I cannot seem to find an actual executable.
There doesn't seem to be any documentation (or maybe I missed it) but what am I doing wrong?

Thanks.

**Comment by slajerek** [comment]
Please post the build log here

**Comment by cbmeeks** [comment]
That was a few days ago.  How do I find the logs?
Thanks

**Comment by slajerek** [comment]
This project uses regular CMake build setup, have you checked

```mdkir build
cd build
cmake ..
make
```

then the retrodebugger binary should be in the build folder.
