### ISSUE TITLE
Bad Line Timings seem incorrect (shifted) when comparing to what the VIC2.txt states

### ISSUE THREAD

**Issue by paich64** [slajerek/RetroDebugger#62]
**Describe the bug**
Machine PAL, Bad Line, No sprites.
running a program cycle by cycle when on a bad line, it looks like the bad line timings reported by The CPU counters are the following:
12 r/w cycles 
  3 w only cycles 
40 cycles stolen by vic2 (43 if the above 3 w only cycles can't be used by any instruction)
  8 r/w cycles 

However, according to the vic2.txt doc (https://www.zimmers.net/cbmpics/cbm/c64/vic-ii.txt) the timings should be : 

11 r/w cycles 
  3 w only cycles 
40 cycles stolen by vic2 (43 if the above 3 w only cycles can't be used by any instruction)
  9 r/w cycles 
 
**To Reproduce**
1. Load the .prg in attachement
2. run it using SYS4096
3. Hit F10 to stop the execution
4. Using the VIC2 screen, explore the CPU timings on raster line $83 (which is a badline) and notice the discrepancy that i have reflected in the big picture I have uploaded

**Expected behavior**
Unless I'm wrong, according to the VIC2.txt doc, there should be 11 r/w cycles (not 12) at the beginning of the badline, and 9 r/w cycles (not 8) at the end of the badline.

**Screenshots**

![VicTimingIssueInRetroDebuggerOnBadLine](https://github.com/user-attachments/assets/bef00513-ec09-47c8-a145-ce1b02105c10)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version : 0.64.68

**Additional context**

[rastcolor1.zip](https://github.com/user-attachments/files/16742199/rastcolor1.zip)

**Comment by paich64** [comment]
Reviewing again and again I think a made an interpretation mistake : I assumed that because CC transitionned from 02 to 01 on cycle when transitionning VC from 0A to 0B meant that LDX#$08 had used cycle 11 as its very first cycle. Which is definitely wrong. 
Actually LDX #$08 starts at cycle 54 and ends at cycle 55. This means that we have : 

cycles 0-10 (11 cycles) 
cycles 11-53 (43 cycles) - including our 3 W cycles
cycles 54-62 - 9 cycles

It's all OK. I apologize for having misinterpreted the retrodebugger figures :/

**Comment by slajerek** [comment]
@paich64  thanks!

OK! No worries, it happens to me also all the time :) Thanks for checking this carefully.
