### ISSUE TITLE
GUI blank frames + offset

### ISSUE THREAD

**Issue by fieserWolF** [slajerek/RetroDebugger#7]
**Describe the bug**
Each window has got a black frame at the top and at the right of it. There is an offset of the mouse-pointer exactly the size of this frame. If you click on an item, another area of the window is activated. You can see it in the screenshots when trying to close a window (first screenshot) or when accessing the pull-down menu (second screenshot).

**Desktop (please complete the following information):**
 - OS: Linux
 - Version Debian 5.15.5-2 (2021-12-18) x86_64 GNU/Linux
![retrodebugger-01](https://user-images.githubusercontent.com/27900786/149542565-af90c463-3a06-4c0e-b257-5e82167a4433.jpg)
![retrodebugger-02](https://user-images.githubusercontent.com/27900786/149542569-8f38c74d-a222-40d2-86f9-9f0a7d263f4e.jpg)

**Comment by slajerek** [comment]
This may be related to DPI problem. I've added a patch to ImGui docking branch code to allow multiple monitors and DPIs but it seems it is not always working correctly. I'll revert the patch and then we can check again if this still happens. The patch may need tweaks then...

**Comment by soenkesmiletzki** [comment]
I also get this error with Ubuntu and latest file :-(
Any chance to fix this?

**Comment by slajerek** [comment]
Please check if recent version fixes this problem
