### ISSUE TITLE
CGuiView.h appears to be missing

### ISSUE THREAD

**Issue by trilogysci** [slajerek/RetroDebugger#72]
**Describe the bug**
While trying to build RetroDebugger-0.64.68. I noticed 2 things
1. CViewC64AllGraphics.cpp was still referenced by CMakeLists.txt, but I think that was removed in master
2. CGuiView.h is included by a number of files but I don't see that anywhere

Also, it appears that the following are also needed (at least for Debian 12 )
* libgtk-3-dev
* libasound2-dev

**Comment by slajerek** [comment]
https://github.com/slajerek/MTEngineSDL/blob/master/src/Engine/GUI/Controls/CGuiView.h

**Comment by trilogysci** [comment]
ok I see its tightly coupled to MTEngineSDL

**Comment by slajerek** [comment]
Yes, correct. Hope in next version we will have a bit better make files and engine added as submodule. I will check the other problem with AllGraphics. I think I removed it indeed 😏 just forgot about it.
